from dotenv import load_dotenv

load_dotenv()


#from langchain.chat_models import init_chat_model
#model = init_chat_model(model="mistral-large-dataset" , model_provider="grok")

from langchain_mistralai import ChatMistralAI

mistral_model = ChatMistralAI(
    model = "mistral-large-latest"
)

print("Mistral: ")
print(mistral_model.invoke("What date is Today").content)

#Temperature controls the randomness and creativity of the text generated by model

from langchain_google_genai import ChatGoogleGenerativeAI

gemini_model = ChatGoogleGenerativeAI(model = "gemini-2.5-flash" , temperature = 0.8)
response = gemini_model.invoke("Tell me about ML")
print("\n")
print("Gemini: ")
print(response.content)

